# Generated by Django 4.2.27 on 2026-01-31 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20220227_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubTrending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('author', models.CharField(db_index=True, max_length=100, verbose_name='作者')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='项目名称')),
                ('full_name', models.CharField(max_length=300, verbose_name='完整名称')),
                ('url', models.URLField(max_length=500, verbose_name='项目地址')),
                ('description', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('language', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='编程语言')),
                ('stars', models.IntegerField(default=0, verbose_name='Star 数')),
                ('forks', models.IntegerField(default=0, verbose_name='Fork 数')),
                ('current_period_stars', models.IntegerField(default=0, verbose_name='今日新增 Star')),
                ('avatar', models.URLField(blank=True, max_length=500, null=True, verbose_name='作者头像')),
                ('collection_date', models.DateField(db_index=True, verbose_name='采集日期')),
                ('since', models.CharField(default='daily', max_length=20, verbose_name='时间范围')),
                ('ai_analysis', models.JSONField(blank=True, null=True, verbose_name='AI 分析结果')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='额外数据')),
            ],
            options={
                'verbose_name': 'GitHub 热门项目',
                'verbose_name_plural': 'GitHub 热门项目',
                'ordering': ['-collection_date', '-current_period_stars'],
            },
        ),
        migrations.AlterModelOptions(
            name='historicaldict',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 字典', 'verbose_name_plural': 'historical 字典'},
        ),
        migrations.AlterField(
            model_name='dict',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dicttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL, verbose_name='最后编辑人'),
        ),
        migrations.AlterField(
            model_name='historicaldict',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldict',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
